version: 2

sources:
  - name: norm
    schema: norm
    tables:
     - name: t_employee
     - name: t_region
     - name: t_customer
     - name: t_segment

models:
  - name: dim_date
    description: Date dimension table
  - name: dim_employee
    description: >
      Dimension table for the employees. Each record represents the state of
      an employee between the dates `valid_from` and `valid_to`. If `valid_to`
      is NULL, then that record is the currently active one.
    columns:
      - name: sk_employee
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: employee_id
        description: "A unique identifier for the employee"
      - name: employee_name
        description: "The name of the employee"
      - name: region
        description: "The region this employee is responsible for"
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime. If this is NULL, then this is the currently active version."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."
  - name: dim_customer
    description: >
      Dimension table for the customers. Each record represents the state of
      a customer between the dates `valid_from` and `valid_to`. If `valid_to`
      is NULL, then that record is the currently active one.
    columns:
      - name: sk_customer
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "A unique identifier for the customer"
      - name: customer_name
        description: "The name of the customer"
      - name: segment
        description: "The segment this customer belongs to"
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime. If this is NULL, then this is the currently active version."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."
  - name: dim_geography
    description: >
      Geogrpahy dimension table. Each record represents the state of
      a city between the dates `valid_from` and `valid_to`. If `valid_to`
      is NULL, then that record is the currently active one.
    columns:
      - name: sk_geography
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: city_id
        description: "A unique identifier for the city"
      - name: city_name
        description: "The name of the city"
      - name: state
        description: "The state this city belongs to"
      - name: region
        description: "The region this city belongs to"
      - name: country
        description: "The country this city belongs to"
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime. If this is NULL, then this is the currently active version."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."
